# Generated by Django 6.0.4 on 2026-05-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Araç Adı / Modeli')),
                ('capacity', models.CharField(help_text='Örn: 500 kişilik servis', max_length=120, verbose_name='Kapasite')),
                ('icon', models.CharField(default='bi-truck', max_length=80, verbose_name='Bootstrap Icon Sınıfı')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araç Filosu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('short_description', models.CharField(max_length=200, verbose_name='Kısa Açıklama')),
                ('icon', models.CharField(default='bi-cup-hot', help_text='https://icons.getbootstrap.com', max_length=80, verbose_name='Bootstrap Icon Sınıfı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Bölge / Şehir')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Not')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Hizmet Bölgesi',
                'verbose_name_plural': 'Hizmet Bölgeleri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Onmer Yemek Organizasyon', max_length=120, verbose_name='Firma Adı')),
                ('tagline', models.CharField(default='Premium Catering & Toplu Yemek Hizmetleri', max_length=200, verbose_name='Slogan')),
                ('hero_title', models.CharField(default='Lezzeti Sanata Dönüştürüyoruz', max_length=200, verbose_name='Hero Başlığı')),
                ('hero_subtitle', models.CharField(default='Düğün, nişan, kurumsal organizasyon ve toplu yemek hizmetlerinde 20+ yıllık deneyim.', max_length=300, verbose_name='Hero Alt Başlık')),
                ('phone', models.CharField(default='+90 555 123 45 67', max_length=30, verbose_name='Telefon')),
                ('whatsapp', models.CharField(default='905551234567', help_text='Sadece rakam, başında ülke kodu ile.', max_length=30, verbose_name='WhatsApp Numarası')),
                ('email', models.EmailField(default='info@onmeryemek.com', max_length=254, verbose_name='E-posta')),
                ('address', models.CharField(default='Kadıköy, İstanbul, Türkiye', max_length=255, verbose_name='Adres')),
                ('google_maps_embed', models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d96363.07!2d29.0!3d40.99!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cab9b40521e5cd%3A0x0!2zS2FkxLFrw7Z5!5e0!3m2!1str!2str!4v1700000000000', help_text='Google Maps iframe src değerini buraya yapıştırın.', verbose_name='Google Maps Embed URL')),
                ('instagram', models.URLField(blank=True, default='https://instagram.com/onmeryemek', verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, default='https://facebook.com/onmeryemek', verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, default='https://twitter.com/onmeryemek', verbose_name='Twitter / X')),
                ('youtube', models.URLField(blank=True, default='https://youtube.com/@onmeryemek', verbose_name='YouTube')),
                ('about_short', models.TextField(default='Onmer Yemek Organizasyon, lezzeti sanatla buluşturan premium bir catering markasıdır.', verbose_name='Kısa Hakkımızda')),
                ('about_long', models.TextField(default='20 yılı aşkın tecrübemizle düğünlerden kurumsal organizasyonlara, toplu yemek servislerinden özel davetlere kadar her boyuttaki etkinlik için kusursuz lezzetler hazırlıyoruz. Mutfağımızda yalnızca taze ve kaliteli malzemeler kullanırız.', verbose_name='Detaylı Hakkımızda')),
                ('mission', models.TextField(default='Misafirlerimize yalnızca yemek değil, unutulmaz bir deneyim sunmak; hijyen, lezzet ve sunum standartlarımızı her organizasyonda en üst seviyede tutmaktır.', verbose_name='Misyonumuz')),
                ('vision', models.TextField(default='Türkiye’nin en güvenilir premium catering markası olmak ve sektöre kalite çıtasını yükselten bir referans kazandırmak.', verbose_name='Vizyonumuz')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Etiket')),
                ('value', models.PositiveIntegerField(verbose_name='Değer')),
                ('suffix', models.CharField(blank=True, help_text='Örn: +, %, K', max_length=8, verbose_name='Sonek')),
                ('icon', models.CharField(default='bi-award', help_text='https://icons.getbootstrap.com adresinden seçin.', max_length=80, verbose_name='Bootstrap Icon Sınıfı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'İstatistik',
                'verbose_name_plural': 'İstatistikler',
                'ordering': ['order'],
            },
        ),
    ]
