# Generated by Django 6.0.4 on 2026-05-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='google_maps_embed',
            field=models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d96363.07!2d29.0!3d40.99!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cab9b40521e5cd%3A0x0!2zS2FkxLFrw7Z5!5e0!3m2!1str!2str!4v1700000000000', help_text='Google Maps iframe src adresini buraya yapıştırın.', verbose_name='Google Maps URL'),
        ),
    ]
