# Generated by Django 6.0.4 on 2026-05-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('time', models.TimeField(verbose_name='Saat')),
                ('topic', models.CharField(blank=True, help_text='Düğün, kurumsal etkinlik, catering vs.', max_length=160, verbose_name='Görüşme Konusu')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal'), ('done', 'Tamamlandı')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['-date', '-time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('date', 'time'), name='unique_active_reservation_slot')],
            },
        ),
    ]
