# Generated by Django 6.0.4 on 2026-06-14 20:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Ürün adı')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('lt', 'Litre'), ('ml', 'Mililitre'), ('adet', 'Adet'), ('paket', 'Paket'), ('kutu', 'Kutu')], default='kg', max_length=10, verbose_name='Birim')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Mevcut miktar')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Bu seviyenin altında uyarı gösterilir.', max_digits=12, verbose_name='Minimum stok')),
                ('notes', models.TextField(blank=True, verbose_name='Not')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stok kalemi',
                'verbose_name_plural': 'Stok kalemleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Giriş'), ('out', 'Çıkış'), ('adjust', 'Düzeltme')], max_length=10, verbose_name='Tür')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miktar')),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='İşlem sonrası bakiye')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi yapan')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem', verbose_name='Stok kalemi')),
            ],
            options={
                'verbose_name': 'Stok hareketi',
                'verbose_name_plural': 'Stok hareketleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
