# Generated by Django 6.0.4 on 2026-05-07 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('category', models.CharField(choices=[('wedding', 'Düğün'), ('engagement', 'Nişan'), ('corporate', 'Kurumsal'), ('bulk', 'Toplu Yemek'), ('catering', 'Catering'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Kategori')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='Konum')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Etkinlik Tarihi')),
                ('cover', models.ImageField(upload_to='portfolio/covers/', verbose_name='Kapak Görseli')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolyo Öğesi',
                'verbose_name_plural': 'Portfolyo Öğeleri',
                'ordering': ['order', '-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/images/', verbose_name='Görsel')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Başlık / Alt Metin')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolioitem', verbose_name='Portfolyo Öğesi')),
            ],
            options={
                'verbose_name': 'Galeri Görseli',
                'verbose_name_plural': 'Galeri Görselleri',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
