# Generated by Django 6.0.4 on 2026-05-07 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Ad')),
                ('kind', models.CharField(choices=[('wedding', 'Düğün'), ('engagement', 'Nişan'), ('corporate', 'Şirket Organizasyonu'), ('bulk', 'Toplu Yemek'), ('catering', 'Catering'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Tür')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('icon', models.CharField(default='bi-egg-fried', max_length=80, verbose_name='Bootstrap Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Yemek Kategorisi',
                'verbose_name_plural': 'Yemek Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Örn: 12 - 18 Mayıs Haftası Menüsü', max_length=120, verbose_name='Başlık')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Özet')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Haftalık Menü',
                'verbose_name_plural': 'Haftalık Menüler',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Yemek Adı')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('ingredients', models.CharField(blank=True, help_text='Virgülle ayırarak yazınız.', max_length=255, verbose_name='İçindekiler')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kalori (kcal)')),
                ('serving_size', models.CharField(blank=True, help_text='Örn: 250 gr / kişi', max_length=60, verbose_name='Porsiyon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Görsel')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='menu.menucategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Yemek',
                'verbose_name_plural': 'Yemekler',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Pazartesi'), ('tue', 'Salı'), ('wed', 'Çarşamba'), ('thu', 'Perşembe'), ('fri', 'Cuma'), ('sat', 'Cumartesi'), ('sun', 'Pazar')], max_length=4, verbose_name='Gün')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Fiyat (₺)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Not')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_appearances', to='menu.dish', verbose_name='Yemek')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.weeklymenu', verbose_name='Menü')),
            ],
            options={
                'verbose_name': 'Menü Kalemi',
                'verbose_name_plural': 'Menü Kalemleri',
                'ordering': ['day', 'order'],
            },
        ),
    ]
