# Generated by Django 6.0.4 on 2026-05-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Toplu sipariş formundaki kişi başı fiyat.', max_digits=8, verbose_name='Kişi Başı Fiyat (₺)'),
        ),
    ]
