# Generated by Django 6.0.4 on 2026-05-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='Firma')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('organization_type', models.CharField(choices=[('wedding', 'Düğün'), ('engagement', 'Nişan'), ('corporate', 'Şirket Organizasyonu'), ('bulk', 'Toplu Yemek'), ('catering', 'Catering'), ('other', 'Diğer')], default='catering', max_length=20, verbose_name='Organizasyon Türü')),
                ('guest_count', models.PositiveIntegerField(verbose_name='Kişi Sayısı')),
                ('event_date', models.DateField(verbose_name='Etkinlik Tarihi')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Etkinlik Saati')),
                ('event_address', models.CharField(blank=True, max_length=255, verbose_name='Etkinlik Adresi')),
                ('notes', models.TextField(blank=True, verbose_name='Özel Notlar')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('contacted', 'İletişime Geçildi'), ('confirmed', 'Onaylandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='new', max_length=20, verbose_name='Durum')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tahmini Fiyat (₺)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
            ],
            options={
                'verbose_name': 'Sipariş Talebi',
                'verbose_name_plural': 'Sipariş Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
