# Generated by Django 6.0.4 on 2026-05-09 12:21

from django.db import migrations, models
from django.db.models import F


def mark_existing_orders_paid(apps, schema_editor):
    """Rows created before checkout: mark paid so they are not stuck pending."""
    Order = apps.get_model('orders', 'Order')
    Order.objects.all().update(
        payment_status='paid',
        payment_transaction_ref='ONMER-LEGACY',
        payment_completed_at=F('created_at'),
    )


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ödeme Bekleniyor'), ('paid', 'Ödeme Alındı'), ('failed', 'Ödeme Başarısız')], default='pending', max_length=16, verbose_name='Ödeme Durumu'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction_ref',
            field=models.CharField(blank=True, help_text='Ödeme sağlayıcısından dönen veya simüle edilen işlem no.', max_length=64, verbose_name='Ödeme Referansı'),
        ),
        migrations.RunPython(mark_existing_orders_paid, _noop),
    ]
